repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-added-large-files # Verifica archivos grandes
      - id: check-case-conflict # Verifica conflictos de nombres de archivo
      - id: check-merge-conflict # Verifica conflictos de fusión
      - id: check-yaml # Verifica sintaxis y estructura YAML
      - id: debug-statements # Busca declaraciones de depuración
      - id: end-of-file-fixer # Añade una línea en blanco al final de los archivos
      - id: trailing-whitespace # Elimina espacios en blanco al final de líneas

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        # language_version: python3.11

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.7"
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.17.1"
    hooks:
      - id: mypy
        files: ^src/
        args: []
        additional_dependencies: ["pydantic", "pydantic-settings"]

  - repo: https://github.com/PyCQA/bandit
    rev: "1.8.6"
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml", "--exclude", "tests"]

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.0.0
    hooks:
      - id: cspell
        additional_dependencies:
          - "@cspell/dict-es-es"
        name: Check spelling in code and docs
        args: ["--gitignore", "--show-context", "--show-suggestions"]

  - repo: local
    hooks:
      - id: cspell-commit-msg
        name: Check spelling in commit message
        entry: cspell
        language: node
        stages: [commit-msg]
        args: ["--locale=es,en", "--config=.cspell.json", "--no-progress", "--"]
        pass_filenames: false
        additional_dependencies: ["cspell"]
